/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangtheman;

/**
 *
 * @author msi
 */
public class HangmanJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HangmanJFrame
     */
    public HangmanJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Abtn = new javax.swing.JButton();
        Bbtn = new javax.swing.JButton();
        Cbtn = new javax.swing.JButton();
        Ebtn = new javax.swing.JButton();
        Gbtn = new javax.swing.JButton();
        Dbtn = new javax.swing.JButton();
        Hbtn = new javax.swing.JButton();
        Ibtn = new javax.swing.JButton();
        Jbtn = new javax.swing.JButton();
        Kbtn = new javax.swing.JButton();
        Mbtn = new javax.swing.JButton();
        Fbtn = new javax.swing.JButton();
        Nbtn = new javax.swing.JButton();
        Obtn = new javax.swing.JButton();
        Pbtn = new javax.swing.JButton();
        Qbtn = new javax.swing.JButton();
        Rbtn = new javax.swing.JButton();
        Sbtn = new javax.swing.JButton();
        Ubtn = new javax.swing.JButton();
        Lbtn = new javax.swing.JButton();
        Vbtn = new javax.swing.JButton();
        Wbtn = new javax.swing.JButton();
        Xbtn = new javax.swing.JButton();
        Ybtn = new javax.swing.JButton();
        Zbtn = new javax.swing.JButton();
        Tbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ScorejTextField1 = new javax.swing.JTextField();
        Score = new javax.swing.JLabel();
        pic_H = new javax.swing.JLabel();
        pic_D = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        pic3 = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        Answer1 = new javax.swing.JTextField();
        Answer2 = new javax.swing.JTextField();
        Answer3 = new javax.swing.JTextField();
        Answer4 = new javax.swing.JTextField();
        Answer5 = new javax.swing.JTextField();
        Question1 = new javax.swing.JLabel();
        Question2 = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        Question4 = new javax.swing.JLabel();
        Question5 = new javax.swing.JLabel();
        jLab_W = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Abtn.setBackground(new java.awt.Color(255, 51, 51));
        Abtn.setText("A");
        Abtn.setPreferredSize(new java.awt.Dimension(75, 25));
        Abtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Abtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 50, 20));

        Bbtn.setBackground(new java.awt.Color(255, 153, 255));
        Bbtn.setText("B");
        Bbtn.setMaximumSize(new java.awt.Dimension(75, 25));
        Bbtn.setMinimumSize(new java.awt.Dimension(50, 25));
        Bbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Bbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 50, 20));

        Cbtn.setBackground(new java.awt.Color(255, 51, 51));
        Cbtn.setText("C");
        Cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Cbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 50, 20));

        Ebtn.setBackground(new java.awt.Color(255, 51, 51));
        Ebtn.setText("E");
        Ebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Ebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 450, 50, 20));

        Gbtn.setBackground(new java.awt.Color(255, 51, 51));
        Gbtn.setText("G");
        Gbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Gbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 50, 20));

        Dbtn.setBackground(new java.awt.Color(255, 153, 255));
        Dbtn.setText("D");
        Dbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Dbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 50, 20));

        Hbtn.setBackground(new java.awt.Color(255, 153, 255));
        Hbtn.setText("H");
        Hbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Hbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 50, 20));

        Ibtn.setBackground(new java.awt.Color(255, 51, 51));
        Ibtn.setText("I");
        Ibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Ibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 50, 20));

        Jbtn.setBackground(new java.awt.Color(255, 153, 255));
        Jbtn.setText("J");
        Jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Jbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 50, 20));

        Kbtn.setBackground(new java.awt.Color(255, 51, 51));
        Kbtn.setText("K");
        Kbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Kbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 50, 20));

        Mbtn.setBackground(new java.awt.Color(255, 51, 51));
        Mbtn.setText("M");
        Mbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Mbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 50, 20));

        Fbtn.setBackground(new java.awt.Color(255, 153, 255));
        Fbtn.setText("F");
        Fbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Fbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 50, 20));

        Nbtn.setBackground(new java.awt.Color(255, 153, 255));
        Nbtn.setText("N");
        Nbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Nbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, 50, 20));

        Obtn.setBackground(new java.awt.Color(255, 51, 51));
        Obtn.setText("O");
        Obtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObtnActionPerformed(evt);
            }
        });
        getContentPane().add(Obtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 510, 50, 20));

        Pbtn.setBackground(new java.awt.Color(255, 153, 255));
        Pbtn.setText("P");
        Pbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Pbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 540, 50, 20));

        Qbtn.setBackground(new java.awt.Color(255, 51, 51));
        Qbtn.setText("Q");
        Qbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Qbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 50, 20));

        Rbtn.setBackground(new java.awt.Color(255, 153, 255));
        Rbtn.setText("R");
        Rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Rbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 540, 50, 20));

        Sbtn.setBackground(new java.awt.Color(255, 51, 51));
        Sbtn.setText("S");
        Sbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Sbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 50, 20));

        Ubtn.setBackground(new java.awt.Color(255, 51, 51));
        Ubtn.setText("U");
        Ubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Ubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 570, 50, 20));

        Lbtn.setBackground(new java.awt.Color(255, 153, 255));
        Lbtn.setText("L");
        Lbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Lbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 50, 20));

        Vbtn.setBackground(new java.awt.Color(255, 153, 255));
        Vbtn.setText("V");
        Vbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Vbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 50, 20));

        Wbtn.setBackground(new java.awt.Color(255, 51, 51));
        Wbtn.setText("W");
        Wbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Wbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 50, 20));

        Xbtn.setBackground(new java.awt.Color(255, 153, 255));
        Xbtn.setText("X");
        Xbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Xbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 50, 20));

        Ybtn.setBackground(new java.awt.Color(255, 51, 51));
        Ybtn.setText("Y");
        Ybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Ybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 570, 50, 20));

        Zbtn.setBackground(new java.awt.Color(255, 153, 255));
        Zbtn.setText("Z");
        Zbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Zbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 600, 170, 20));

        Tbtn.setBackground(new java.awt.Color(255, 153, 255));
        Tbtn.setText("T");
        Tbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Tbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 50, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Type your word :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 414, 290, 30));
        getContentPane().add(ScorejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 60, 30));

        Score.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Score.setForeground(new java.awt.Color(255, 255, 255));
        Score.setText("Score :");
        getContentPane().add(Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 350, 60, 30));

        pic_H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/pic_H.jpg"))); // NOI18N
        getContentPane().add(pic_H, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 310, 300));

        pic_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/save.png"))); // NOI18N
        getContentPane().add(pic_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 160, 350));

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/Hangman1.png"))); // NOI18N
        getContentPane().add(pic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 60, 50));

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/Hangman3.png"))); // NOI18N
        getContentPane().add(pic2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 70, 50));

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/Hangman4.png"))); // NOI18N
        getContentPane().add(pic3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 60, 70));

        pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/Hangman5.png"))); // NOI18N
        getContentPane().add(pic4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 50, 120));

        Answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1ActionPerformed(evt);
            }
        });
        getContentPane().add(Answer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 370, 30));

        Answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer2ActionPerformed(evt);
            }
        });
        getContentPane().add(Answer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 370, 30));

        Answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer3ActionPerformed(evt);
            }
        });
        getContentPane().add(Answer3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 370, 30));

        Answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer4ActionPerformed(evt);
            }
        });
        getContentPane().add(Answer4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 360, 30));

        Answer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer5ActionPerformed(evt);
            }
        });
        getContentPane().add(Answer5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 360, 30));

        Question1.setBackground(new java.awt.Color(255, 51, 51));
        Question1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Question1.setForeground(new java.awt.Color(255, 255, 255));
        Question1.setText("What is the taller animal in the planet ?");
        getContentPane().add(Question1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 290, 30));

        Question2.setBackground(new java.awt.Color(255, 51, 51));
        Question2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Question2.setForeground(new java.awt.Color(255, 255, 255));
        Question2.setText("What is the sun's color?");
        getContentPane().add(Question2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 290, 30));

        Question3.setBackground(new java.awt.Color(255, 51, 51));
        Question3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Question3.setForeground(new java.awt.Color(255, 255, 255));
        Question3.setText("Where is Montreal located?");
        getContentPane().add(Question3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 290, 30));

        Question4.setBackground(new java.awt.Color(255, 51, 51));
        Question4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Question4.setForeground(new java.awt.Color(255, 255, 255));
        Question4.setText("where is the longest river located?");
        getContentPane().add(Question4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 290, 30));

        Question5.setBackground(new java.awt.Color(255, 51, 51));
        Question5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Question5.setForeground(new java.awt.Color(255, 255, 255));
        Question5.setText("How many Quarters does the bascetball contain?");
        getContentPane().add(Question5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 360, 30));

        jLab_W.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLab_W.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLab_W, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 170));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangtheman/Hangman22.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    private void reset(){
        
        Question2.setText(null);
        Question3.setText(null);
        Question4.setText(null);
        Question5.setText(null);
        
        
        Answer2.setText(null);
        Answer3.setText(null);
        Answer4.setText(null);
        Answer5.setText(null);
        
        pic_H.setText(null);
        pic_D.setText(null);
        pic1.setText(null);
        pic2.setText(null);
        pic3.setText(null);
        pic4.setText(null);
        
    }
    
    private void ZbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZbtnActionPerformed
        
         String EnterLettter5 = Answer5.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter1 = Answer1.getText();
        
 
         
         if("".equals(EnterLettter5))
        {
            
             Answer5.setText(Zbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Zbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            
             Answer4.setText(Zbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Zbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            
             Answer3.setText(Zbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Zbtn.getText();
            Answer3.setText(EnterLettter3);
        }
        
         
         if("".equals(EnterLettter2))
        {
            
             Answer2.setText(Zbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Zbtn.getText();
            Answer2.setText(EnterLettter2);
        }
        
       
        
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Zbtn.getText());
           
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Zbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_ZbtnActionPerformed

    
    private void AbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbtnActionPerformed
        String EnterLettter1 = Answer1.getText();
        String EnterLettter2 = Answer2.getText();
        String EnterLettter3 = Answer3.getText();
        String EnterLettter4 = Answer4.getText();
        String EnterLettter5 = Answer5.getText();
   
        
        if("".equals(EnterLettter5))
        {
            Answer5.setText(Abtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Abtn.getText();
            Answer5.setText(EnterLettter5);
        }
        
        if("".equals(EnterLettter4))
        {
            Answer4.setText(Abtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Abtn.getText();
            Answer4.setText(EnterLettter4);
        }
        
        if("".equals(EnterLettter3))
        {
            Answer3.setText(Abtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Abtn.getText();
            Answer3.setText(EnterLettter3);
        }
        
        if("".equals(EnterLettter2))
        {
            Answer2.setText(Abtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Abtn.getText();
            Answer2.setText(EnterLettter2);
        }
        
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Abtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Abtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_AbtnActionPerformed

    private void BbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
      
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Bbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Bbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
           if("".equals(EnterLettter4))
        {
            Answer4.setText(Bbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Bbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
          if("".equals(EnterLettter3))
        {
            Answer3.setText(Bbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Bbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Bbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Bbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Bbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Bbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_BbtnActionPerformed

    private void CbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
   
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Cbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Cbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Cbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Cbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Cbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Cbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Cbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Cbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Cbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Cbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_CbtnActionPerformed

    private void DbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
   
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Dbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Dbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Dbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Dbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Dbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Dbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Dbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Dbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Dbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Dbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_DbtnActionPerformed

    private void EbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
       
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Ebtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Ebtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
          if("".equals(EnterLettter4))
        {
            Answer4.setText(Ebtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Ebtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Ebtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Ebtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
          if("".equals(EnterLettter2))
        {
            Answer2.setText(Ebtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Ebtn.getText();
            Answer2.setText(EnterLettter2);
        }
        
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Ebtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Ebtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_EbtnActionPerformed

    private void FbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
 
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Fbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Fbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Fbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Fbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Fbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Fbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Fbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Fbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Fbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Fbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_FbtnActionPerformed

    private void GbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
     
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Gbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Gbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Gbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Gbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Gbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Gbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Gbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Gbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Gbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Gbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_GbtnActionPerformed

    private void HbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbtnActionPerformed
         
          String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();

         if("".equals(EnterLettter5))
        {
            Answer5.setText(Hbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Hbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Hbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Hbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Hbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Hbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Hbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Hbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Hbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Hbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_HbtnActionPerformed

    private void IbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbtnActionPerformed
        
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
 
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Ibtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Ibtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Ibtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Ibtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Ibtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Ibtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Ibtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Ibtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Ibtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Ibtn.getText();
            Answer1.setText(EnterLettter1);
        }
        
    }//GEN-LAST:event_IbtnActionPerformed

    private void JbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnActionPerformed
         
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
  
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Jbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Jbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Jbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Jbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Jbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Jbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Jbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Jbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Jbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Jbtn.getText();
            Answer1.setText(EnterLettter1);
        }
        
    }//GEN-LAST:event_JbtnActionPerformed

    private void KbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
   
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Kbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Kbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Kbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Kbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Kbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Kbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Kbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Kbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Kbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Kbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_KbtnActionPerformed

    private void LbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();

         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Lbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Lbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Lbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Lbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Lbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Lbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Lbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Lbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Lbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Lbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_LbtnActionPerformed

    private void MbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
   
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Mbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Mbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Mbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Mbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Mbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Mbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Mbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Mbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Mbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Mbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_MbtnActionPerformed

    private void NbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
     
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Nbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Nbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Nbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Nbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Nbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Nbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Nbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Nbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Nbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Nbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_NbtnActionPerformed

    private void ObtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
 
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Obtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Obtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Obtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Obtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Obtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Obtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Obtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Obtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Obtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Obtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_ObtnActionPerformed

    private void PbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
    
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Pbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Pbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Pbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Pbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Pbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Pbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Pbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Pbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Pbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Pbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_PbtnActionPerformed

    private void QbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
 
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Qbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Qbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Qbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Qbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Qbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Qbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Qbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Qbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Qbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Qbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_QbtnActionPerformed

    private void RbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
 
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Rbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Rbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Rbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Rbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Rbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Rbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Rbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Rbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Rbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Rbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_RbtnActionPerformed

    private void SbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
     
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Sbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Sbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Sbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Sbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Sbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Sbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Sbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Sbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Sbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Sbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_SbtnActionPerformed

    private void TbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
     
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Tbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Tbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Tbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Tbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Tbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Tbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Tbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Tbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Tbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Tbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_TbtnActionPerformed

    private void UbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
        
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Ubtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Ubtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Ubtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Ubtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Ubtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Ubtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Ubtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Ubtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Ubtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Ubtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_UbtnActionPerformed

    private void VbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
        
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Vbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Vbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Vbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Vbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Vbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Vbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Vbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Vbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Vbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Vbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_VbtnActionPerformed

    private void WbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
  
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Wbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Wbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Wbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Wbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Wbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Wbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Wbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Wbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Wbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Wbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_WbtnActionPerformed

    private void XbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
         
       
         
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Xbtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Xbtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Xbtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Xbtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Xbtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Xbtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Xbtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Xbtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Xbtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Xbtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_XbtnActionPerformed

    private void YbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YbtnActionPerformed
         String EnterLettter1 = Answer1.getText();
         String EnterLettter2 = Answer2.getText();
         String EnterLettter3 = Answer3.getText();
         String EnterLettter4 = Answer4.getText();
         String EnterLettter5 = Answer5.getText();
         
        
     
         if("".equals(EnterLettter5))
        {
            Answer5.setText(Ybtn.getText());
        }
        else
        {
            EnterLettter5 = Answer5.getText() + Ybtn.getText();
            Answer5.setText(EnterLettter5);
        }
         
         if("".equals(EnterLettter4))
        {
            Answer4.setText(Ybtn.getText());
        }
        else
        {
            EnterLettter4 = Answer4.getText() + Ybtn.getText();
            Answer4.setText(EnterLettter4);
        }
         
         if("".equals(EnterLettter3))
        {
            Answer3.setText(Ybtn.getText());
        }
        else
        {
            EnterLettter3 = Answer3.getText() + Ybtn.getText();
            Answer3.setText(EnterLettter3);
        }
         
         if("".equals(EnterLettter2))
        {
            Answer2.setText(Ybtn.getText());
        }
        else
        {
            EnterLettter2 = Answer2.getText() + Ybtn.getText();
            Answer2.setText(EnterLettter2);
        }
         
        if("".equals(EnterLettter1))
        {
            Answer1.setText(Ybtn.getText());
        }
        else
        {
            EnterLettter1 = Answer1.getText() + Ybtn.getText();
            Answer1.setText(EnterLettter1);
        }
    }//GEN-LAST:event_YbtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        pic1.setVisible(false);
        pic2.setVisible(false); 
        pic3.setVisible(false); 
        pic4.setVisible(false); 
        pic_D.setVisible(false);
        pic_H.setVisible(false);
        
        Question2.setVisible(false);
        Question3.setVisible(false);
        Question4.setVisible(false);
        Question5.setVisible(false);
        
     
        Answer2.setVisible(false);
        Answer3.setVisible(false);
        Answer4.setVisible(false);
        Answer5.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    int w = 0;
    private void Answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1ActionPerformed
        String A1 = Answer1.getText();
        String RAnswer1 = "GIRAFFE";
        
        if(A1.equals(RAnswer1))
        {
            jLab_W.setText("" +w);
            Question2.setVisible(true);
            Answer2.setVisible(true);
            Answer1.setEnabled(false);
            
            
        }
        else
        {
            w=w+1;
            jLab_W.setText("" + w);
            Question2.setVisible(true);
            Answer2.setVisible(true);
            Answer1.setEnabled(false);
            
            pic1.setVisible(true);
        }
    }//GEN-LAST:event_Answer1ActionPerformed
  
    private void Answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer2ActionPerformed
        
         String A1 = Answer2.getText();
         String RAnswer2 = "YELLOW";
         int w1 = Integer.parseInt(jLab_W.getText());
         
         if(A1.equals(RAnswer2))
         {
             jLab_W.setText("" + w1);
             Question3.setVisible(true);
             Answer3.setVisible(true);
             Answer2.setEnabled(false);
         }
         else
         {
             w1 = w1+1;
             jLab_W.setText("" + w1);
             Question3.setVisible(true);
             Answer3.setVisible(true);
             Answer2.setEnabled(false);
             
             if(w1==1)
                 pic1.setVisible(true);
             else if(w1==2)
             {
                 pic1.setVisible(true);
                 pic2.setVisible(true);
             }
             
             
         }
         
    }//GEN-LAST:event_Answer2ActionPerformed

    private void Answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer3ActionPerformed
        
         String A3 = Answer3.getText();
         String RAnswer3 = "QUEBEC";
         int w2 = Integer.parseInt(jLab_W.getText());
         
         if(A3.equals(RAnswer3))
         {           
            jLab_W.setText("" + w2);
            Question4.setVisible(true);
            Answer4.setVisible(true);
            Answer3.setEnabled(false);          
         }
         else
         {
            w2 = w2 + 1;
            jLab_W.setText(" " + w2);
         }
         
        switch (w2) {
            case 1:
                pic1.setVisible(true);
                Answer4.setVisible(true);
                Answer3.setEnabled(false);
                Question4.setVisible(true);
                break;
            case 2:
                pic2.setVisible(true);
                Answer4.setVisible(true);
                Answer3.setEnabled(false);
                Question4.setVisible(true);
                break;
            case 3:
                pic2.setVisible(false);
                pic3.setVisible(false);
                pic4.setVisible(false);
                pic_D.setVisible(true);
                Answer3.setEnabled(false);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_Answer3ActionPerformed

    private void Answer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer4ActionPerformed
        
        String A4 = Answer4.getText();
         String RAnswer4 = "AFRICA";
         int w1 = Integer.parseInt(jLab_W.getText());
         
         if(A4.equals(RAnswer4))
         {           
            jLab_W.setText("" + w1);
            Question5.setVisible(true);
            Answer5.setVisible(true);
            Answer4.setEnabled(false);          
         }
         else
         {
            w1 = w1 + 1;
            jLab_W.setText("" + w1);
         }
         
        switch (w1) {
            case 1:
                pic1.setVisible(true);
                Answer5.setVisible(true);
                Answer4.setEnabled(false);
                Question5.setVisible(true);
                break;
            case 2:
                pic2.setVisible(true);
                Answer5.setVisible(true);
                Answer4.setEnabled(false);
                Question5.setVisible(true);
                break;
            case 3:
                pic3.setVisible(false);
                pic4.setVisible(false);
                pic_D.setVisible(true);
                Answer4.setEnabled(false);
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_Answer4ActionPerformed

    private void Answer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer5ActionPerformed
        
        String A5 = Answer5.getText();
         String RAnswer5 = "QUEBEC";
         int w1 = Integer.parseInt(jLab_W.getText());
         
          Answer5.setEnabled(false);
          Answer4.setEnabled(false);  
         
         if(A5.equals(RAnswer5))
         {           
            pic3.setVisible(false);
            pic4.setVisible(false);
            pic_H.setVisible(true);
         }
         else
         {
            w1 = w1 + 1;
            
         
         
            switch (w1) {
                case 1:
                    pic1.setVisible(false);
                    pic3.setVisible(false);
                    pic4.setVisible(false);
                    pic_H.setVisible(true);
                    break;
                case 2:
                    pic2.setVisible(true);
                    pic3.setVisible(false);
                    pic4.setVisible(false);
                    pic_H.setVisible(true);
                    break;
                case 3:
                    pic2.setVisible(true);
                    pic3.setVisible(false);
                    pic_D.setVisible(false);
                    break;
                default:
                    break;
            }
        
    }//GEN-LAST:event_Answer5ActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HangmanJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abtn;
    private javax.swing.JTextField Answer1;
    private javax.swing.JTextField Answer2;
    private javax.swing.JTextField Answer3;
    private javax.swing.JTextField Answer4;
    private javax.swing.JTextField Answer5;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Bbtn;
    private javax.swing.JButton Cbtn;
    private javax.swing.JButton Dbtn;
    private javax.swing.JButton Ebtn;
    private javax.swing.JButton Fbtn;
    private javax.swing.JButton Gbtn;
    private javax.swing.JButton Hbtn;
    private javax.swing.JButton Ibtn;
    private javax.swing.JButton Jbtn;
    private javax.swing.JButton Kbtn;
    private javax.swing.JButton Lbtn;
    private javax.swing.JButton Mbtn;
    private javax.swing.JButton Nbtn;
    private javax.swing.JButton Obtn;
    private javax.swing.JButton Pbtn;
    private javax.swing.JButton Qbtn;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Question2;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Question4;
    private javax.swing.JLabel Question5;
    private javax.swing.JButton Rbtn;
    private javax.swing.JButton Sbtn;
    private javax.swing.JLabel Score;
    private javax.swing.JTextField ScorejTextField1;
    private javax.swing.JButton Tbtn;
    private javax.swing.JButton Ubtn;
    private javax.swing.JButton Vbtn;
    private javax.swing.JButton Wbtn;
    private javax.swing.JButton Xbtn;
    private javax.swing.JButton Ybtn;
    private javax.swing.JButton Zbtn;
    private javax.swing.JLabel jLab_W;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    private javax.swing.JLabel pic_D;
    private javax.swing.JLabel pic_H;
    // End of variables declaration//GEN-END:variables
}
